#!/usr/bin/env bash

# Bash script that creates a PID file, displays "To infinity and beyond"
# indefinitely, and responds to various signals.

# Create PID file
echo "$$" > /var/run/myscript.pid

# Signal handling function
function handle_signal {
  case $1 in
    SIGTERM)
      echo "I hate the kill command"
      rm /var/run/myscript.pid
      exit ;;
    SIGINT)
      echo "Y U no love me?!" ;;
    SIGQUIT)
      rm /var/run/myscript.pid
      exit ;;
  esac
}

# Trap signals
trap 'handle_signal SIGTERM' SIGTERM
trap 'handle_signal SIGINT' SIGINT
trap 'handle_signal SIGQUIT' SIGQUIT

# Infinite loop
while true
do
  echo "To infinity and beyond"
  sleep 2
done
