#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond" indefinitely,
# with a sleep of 2 seconds between each iteration.
# When receiving a SIGTERM signal, display "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
  echo "To infinity and beyond"
  sleep 2
done
