#!/usr/bin/env bash

# Bash script that kills the 7-highlander process.
# Find the PID of the process and kill it.
if pgrep -f "7-highlander" > /dev/null; then
    kill "$(pgrep -f "7-highlander")"
    echo "Process has been killed."
else
    echo "Process not found."
fi
