#!/usr/bin/env bash
# This Bash script groups visitors by IP and HTTP status code, and displays the data in the format:
# OCCURRENCE_NUMBER IP HTTP_CODE
# The data is sorted in descending order based on the number of occurrences.
# This script uses awk to extract the IP and HTTP status code from the Apache log file,
# then uses sort and uniq to count the number of occurrences for each unique IP and HTTP status code combination,
# and finally sorts the data in descending order based on the occurrence number.

awk '{print $1,$9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1,$2,$3}'

