#!/usr/bin/env bash
#This script is displaying the time for 12 hours and 59 minutes
hour=0
while [ $hour -lt 12 ]
do
    echo "Hour: $hour"
    for minute in {1..59}
    do
        printf "%02d:%02d\n" $hour $minute
    done
    ((hour++))
done
echo "Hour: 12"
for minute in {1..59}
do
    printf "%02d:%02d\n" $hour $minute
done
