#!/usr/bin/env bash
#This script is displaying the time for 12 hours and 59 minutes
Hours=0
while [ $Hours -lt 13 ]
do
    minutes=1
    while [ $minutes -lt 60 ]
    do
        printf "%02d:%02d\n" $Hours $minutes
        ((minutes++))
    done
    ((Hours++))
done
