#!/usr/bin/env bash
#This script is displaying the content of the current directotry

for file in *; do
    if [ -f "$file" ] && [[ $file != .* ]] && [[ $file =~ ^[^-]*-(.*)$ ]]; then
        echo "${BASH_REMATCH[1]}"
    fi
done
