#!/usr/bin/env bash
#This script is giving information about the files in the current directory
file="school"
if [ -e "$file" ]
then
	echo "school file exists"
	if [ -s "$file" ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$file" ]
	then
		echo "school is a regular file"
	fi
	if [ -d "$file" ]
	then
		echo "school is a directory"
	fi
	if [ -L "$file" ]
	then
		echo "school is a symbolic link"
	fi
else
	echo "school file does not exist"
fi
